### ISSUE TITLE
Invalid YAML in languages.yaml

### ISSUE THREAD

**Issue by peter-banks** [tranduyhung/grav-theme-clean-blog#11]
Languages contains invalid yaml on lines 28, 68 and 108.

Error:
`"Failed to read languages.yaml: A colon cannot be used in an unquoted mapping value at line 28 (near "HELP: FontAwesome icon class, example: fa-facebook")."`

Example:
`HELP: FontAwesome icon class, example: fa-facebook`
should be 
`HELP: FontAwesome icon class, example fa-facebook`

**Comment by peter-banks** [comment]
Clean blog v.1.4.0
Grav v1.2.4
Apache/2.4.6 (CentOS) PHP/5.6.30

**Comment by tranduyhung** [comment]
Where do you see this error? I have Grav v1.2.4, Admin v1.4.2, Clean Blog v1.4.0 and everything seems fine. Anyway I will improve this in the next release.

**Comment by peter-banks** [comment]
It breaks the site and admin. Attached is the screenshot of the error.
![languages errror](https://cloud.githubusercontent.com/assets/15824945/26517997/0bf2f6a0-42e9-11e7-9fa0-24cf967b4676.png).

I updated Grav and plugins to latest, then updated theme.

**Comment by tranduyhung** [comment]
Thank you for the info! I just released 1.4.1 to fix this.
