### ISSUE TITLE
Possibility to set Social Network Icons with target=“_blank” ?

### ISSUE THREAD

**Issue by gaasen** [tranduyhung/grav-theme-clean-blog#13]
Hi there, you have done a great job with this theme.

I am however experiencing a little niggle wrt. the social network icons on this theme.

When using these, the links simply move the user away from my website for good.
I would prefer if there was an option to open the link in a new tab instead of "loosing the visitor".

I am here thinking of the option to set such links (or all of them ) with the target=“_blank”

**Comment by tranduyhung** [comment]
I will consider this change in the next release. For now, you can add target="_blank" to <a> element in user/themes/clean-blog/templates/partials/footer.html.twig as a temporary solution.

**Comment by gaasen** [comment]
Thanks a lot for the reply. I will indeed apply the temporary solution.
