### ISSUE TITLE
Blog working on other menupages

### ISSUE THREAD

**Issue by gaasen** [tranduyhung/grav-theme-clean-blog#14]
Hi there,
I was just having a small "problem"

The blog seem to work only on my homepage.

In addition to the blog on my homepage I created another page that show up in the top menu.
I then set this page template to be "blog"
I finally added subpages to this page.
The subpages does not show up as blogitems.

Is this a fault, or is the template programmed so that the blog only work for the homepage?

Thanks a lot
Goran

**Comment by tranduyhung** [comment]
Have you set up collection for your page yet? If you don't set this up, no blog posts (child pages) are shown.

You can check the skeleton as example: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-clean-blog/master/pages/01.home/blog.md

More info about collection: https://learn.getgrav.org/content/collections

**Comment by gaasen** [comment]
Thanks a lot,
I am new to Grav, so wasn't aware that I had to set this up to get it to work.

Thanks a lot for the pointer. I got it working within a couple of minutes.

Reg.
Goran
