### ISSUE TITLE
max-width doesn't work

### ISSUE THREAD

**Issue by jnizniowski** [tranduyhung/grav-theme-clean-blog#17]
I found that in `bootstrap.css`, there's an entry:
```
img {
    max-width: 100% !important;
```
but apparently it doesn't work, at least in blog posts. But there's more than one `img` property in this file.
I tried to add this to the `img` that contains `vertical-align: middle;` and it works.

**Comment by tranduyhung** [comment]
You can try to load your images with "img-responsive" class of Bootstrap, for example:

    ![](unsplash_victor_erixon.jpg?classes=img-responsive)

**Comment by tranduyhung** [comment]
I added a new CSS style to do this by default in 1.4.3.

**Comment by Suplanus** [comment]
Changed to `img-fluid`:

```
![Foo](/data/images/foo.webp?classes=img-fluid)
```
