### ISSUE TITLE
Default header image

### ISSUE THREAD

**Issue by Vince42** [tranduyhung/grav-theme-clean-blog#21]
This is probably a total newbie question.
I just installed the theme and want to specify a default header image, but all my attempts to specify a file name, which I used in some pages, failed.
How do I correctly set the default header image?

**Comment by tranduyhung** [comment]
You can set default header image in the theme's configuration.

**Comment by romanbeldacz** [comment]
It's not a bug. You must upload your image to directory: `<your_grav_dir>/user/themes/clean-blog/img/<your_image_name.png>`
And that `<your_image_name.png>` (only name) set in administration on config file.

**Comment by Vince42** [comment]
Okay, I will give it a try and close this issue.

**Comment by Vince42** [comment]
Question seems to be answered.
