### ISSUE TITLE
Blog dates in blog-section and course images in course-overview not displayed correctly

### ISSUE THREAD

**Issue by eurokrl** [tranduyhung/grav-theme-clean-blog#26]
The dates of blogs are not displayed as in the blog page (`posted by <user> <date>`), but rather like this `<user> MoAMCESTEJanuary+0200RJanuaryAMCEST.0+020021 `.
Pictures in the courses-overview page also have different sizes and only small parts of them are displayed.

**Comment by tranduyhung** [comment]
You need to change your date format, here is an example: https://raw.githubusercontent.com/tranduyhung/grav-skeleton-clean-blog/master/pages/01.home/classic-modern-architecture/item.md

There is no template called "courses" or "overview" page in the theme. If you mean that is blog page or blog detail page, the images in these pages are shown like that in the original HTML template.
