### ISSUE TITLE
Social Media Icons layout issue

### ISSUE THREAD

**Issue by aptonline** [tranduyhung/grav-theme-clean-blog#27]
On both Safari (Mac and Ios) and Firefox (Mac) the social media icons in the footer are not displaying correctly. The circles around them are larger than they should be. See below:

![26375B66-151C-4236-9BD0-F14473EBED9D](https://user-images.githubusercontent.com/190136/179395033-949cfe3c-90ce-4a70-a76f-1b290d9c35a8.jpeg)

This is with the latest version (2.0)

**Comment by tranduyhung** [comment]
I don't see this problem on my Safari 15.5 and Firefox 102.1 (all are in the latest versions).

**Comment by aptonline** [comment]
Must have been a bad install,  recreated my install and now working :)
