### ISSUE TITLE
Form submit button has incorrect classes

### ISSUE THREAD

**Issue by pamtbaau** [tranduyhung/grav-theme-clean-blog#33]
In commit https://github.com/tranduyhung/grav-theme-clean-blog/commit/87e246c3be20f89cdf3724e20e3047c52ff59f89 from April 26, 2022, the following has been introduced in template *templates/forms/form.html.twig*
```
{% block button_classes %}
    class="btn-primary text-uppercase disabled {{ button.classes }} "
{% endblock %}
```

There are a few issues with this. The [original Clean Blog](https://startbootstrap.com/previews/clean-blog) uses the following button definition in the Contact page:
```
<button class="btn btn-primary text-uppercase disabled" id="submitButton" type="submit">Send</button>
```

In the definition of the Button in template *templates/forms/form.html.twig*:
- The class `btn` has been forgotten
- Class `disabled` has also been copied. I presume by accident, because the button will now no longer respond to mouse clicks.

By the way, the demo has not been updated to the latest version.

**Comment by tranduyhung** [comment]
Thank for your reporting this. It was fixed in 2.0.1 version.
