### ISSUE TITLE
pagination 'OLDER POSTS →' seems to be missing

### ISSUE THREAD

**Issue by davidtew** [tranduyhung/grav-theme-clean-blog#4]
Hi - on the [home page](http://www.peaceofmindwebsite.com/skeletons/clean-blog/) there isn't any method to paginate to OLDER POSTS →

Compare with the original template: https://blackrockdigital.github.io/startbootstrap-clean-blog/

**Comment by davidtew** [comment]
I see the problem ... the [plugin 'pagination'](https://github.com/getgrav/grav-plugin-pagination) has not been included in the directory 

 `/your/site/grav/user/plugins/pagination`

**Comment by Zettt** [comment]
I also just saw this. Please fix.

**Comment by tranduyhung** [comment]
This was a problem in the skeleton, not in the theme, the skeleton didn't include Pagination plugin, simply install Pagination plugin.

Clean Blog skeleton 1.1.0 already includes Pagination plugin.
