### ISSUE TITLE
Re-use header image

### ISSUE THREAD

**Issue by Zettt** [tranduyhung/grav-theme-clean-blog#6]
I couldn't figure out a way to "re-use" one of the header images. I think it's relatively annoying that I have to upload a new header image for each blog entry. Sometimes I just want to write something without anypictures. Which notation would the theme accept to, say, reference an image from a parent folder, e.g. `../../background.jpg`?

**Comment by tranduyhung** [comment]
In Clean Blog theme 1.2.0, you can set the default header image in the theme's configuration, if you don't assign a header image in your page, this default one is used. Having a page without header image is currently not supported, you need to customize twig and CSS files to achieve that.

**Comment by Zettt** [comment]
Thank you very much, @tranduyhung!
