### ISSUE TITLE
header-image don't appear 

### ISSUE THREAD

**Issue by artdesignment** [tranduyhung/grav-theme-clean-blog#9]
I just tried some different ways to integrate a custom header-image. It's uploaded in my FTP. I have the image `"pik.jpg"` in the 01.home folder. Is it correct to link it like `"![](pik.jpg)"`? Because in the expert view there is given `"header_image: '![](pik.jpg)'"` but it just does not appear. I also tried to integrate it via URL like `"'![](/pages/01.home/pik.jpg)'"` but this also do not work. 
So do you can tell me what I'm doing wrong? 

I also looked into the DeveloperTools and those brackets (' ') where the Markdown or URL-Link to the image should appear, is just empty.

**Comment by tranduyhung** [comment]
In header section you don't need to use Markdown, you just need to set header_image like this:

```
header_image: pik.jpg
```

**Comment by artdesignment** [comment]
Oh, that was too easy. Thank you very much! That worked. 

I just want to notice, that I used drag and drop to "put" the picture into the `background-image` field. So then there is written `![](pik.jpg)` which also means, that this is pasted behind `header_image:`. I mean I understand why this happens. Because so it is possible to just drag the picture in the text field. But wouldn't it enhance the usability if the drag and drop into the `background-image` would "transform" the picture into `pik.jpg` instead of `![](pik.jpg)`. I don't know if this is possible and it might be a Grav issue and not a theme issue. 

Anyway... thanks a lot for you fast answer. I like your theme, good work!
